server.port=8084
spring.application.name=ms-inventario

spring.datasource.url=jdbc:h2:mem:inventariodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none

spring.h2.console.enabled=true

spring.flyway.enabled=true