CREATE TABLE empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(100) NOT NULL,
    cargo VARCHAR(50) NOT NULL,               -- ENUM
    fecha_ingreso DATE DEFAULT CURRENT_DATE,
    local_id BIGINT NOT NULL                  -- El "link" con ms-locales
);


