CREATE TABLE pedidos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_pedido VARCHAR(50) NOT NULL,
    local_id BIGINT,
    mesa_id BIGINT,
    empleado_id BIGINT
);

CREATE TABLE detalles_pedidos(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plato_id BIGINT NOT NULL,
    cantidad INT NOT NULL,
    pedido_id BIGINT,
    CONSTRAINT fk_detalles_pedidos_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(id)
);