CREATE TABLE platos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    local_id BIGINT NOT NULL,
    precio_venta DOUBLE NOT NULL,
    disponible BOOLEAN NOT NULL
);
----Plato 1: Ceviche
INSERT INTO platos (nombre, local_id, precio_venta, disponible)
VALUES ('Ceviche MarFuego', 1, 21000.0, true);

-- Plato 2: Lomo Saltado
INSERT INTO platos (nombre, local_id, precio_venta, disponible)
VALUES ('Lomo Saltado Tradicional', 1, 15000.0, true);
--tabla intermedia
CREATE TABLE plato_productos (
     plato_id BIGINT NOT NULL,
     producto_id BIGINT NOT NULL,
     FOREIGN KEY (plato_id) REFERENCES platos(id) ON DELETE CASCADE
);

-- Ingredientes para el Ceviche (ID 1)
INSERT INTO plato_productos (plato_id, producto_id) VALUES (1, 1); -- Camarones
INSERT INTO plato_productos (plato_id, producto_id) VALUES (1, 2); -- Limón
INSERT INTO plato_productos (plato_id, producto_id) VALUES (1, 3); -- Cebolla

--Ingredientes para el Lomo Saltado (ID 2)
INSERT INTO plato_productos (plato_id, producto_id) VALUES (2, 4); -- Carne
INSERT INTO plato_productos (plato_id, producto_id) VALUES (2, 3); -- Cebolla