CREATE TABLE proveedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    tipo_insumo VARCHAR(50) NOT NULL, --  'MARISCOS', 'VEGETALES', 'CARNES'
    tipo_persona VARCHAR(10) NOT NULL,   --'NATURAL O JURIDICA'
    telefono VARCHAR(20),
    email VARCHAR(50),
    zona VARCHAR(50) NOT NULL,      -- 'Ancud', 'Pelluco', 'Castro'
    estado VARCHAR(15) DEFAULT 'ACTIVO' -- Para deshabilitar si dejan de proveer
);